package pl.kzybala.lab.jitpipeline;

/**
 * The deterministic workload every JIT experiment in this lab shares: a
 * tiny "pricing" computation with exact integer semantics, three concrete
 * implementations behind one interface (the call-site-shape axis:
 * monomorphic / bimorphic / megamorphic), and a fixed input stream
 * generated by the repository-standard xorshift64. Correctness oracle:
 * the shared fixture (fixtures/jit-pipeline-fixtures.json) pins the exact
 * totals for every pricer and for the rotating mix — the Rust AOT
 * baseline computes the identical stream and totals.
 */
public final class PricingKernel {

    public interface Pricer {
        long price(long amount);
    }

    public static final class BasicPricer implements Pricer {
        @Override
        public long price(long amount) {
            return amount * 100;
        }
    }

    public static final class DiscountPricer implements Pricer {
        @Override
        public long price(long amount) {
            return amount * 90 + 5;
        }
    }

    public static final class SurgePricer implements Pricer {
        @Override
        public long price(long amount) {
            return amount * 150 - 3;
        }
    }

    public static final int INPUTS = 1024;
    public static final long SEED = 7;

    private PricingKernel() {}

    /** The fixed input stream: 1 + (xorshift64(seed) % 1000), unsigned math. */
    public static long[] amounts() {
        long[] out = new long[INPUTS];
        long state = Math.max(SEED, 1);
        for (int i = 0; i < INPUTS; i++) {
            state ^= state << 13;
            state ^= state >>> 7;
            state ^= state << 17;
            out[i] = 1 + Long.remainderUnsigned(state, 1000);
        }
        return out;
    }

    /** One pass of the kernel: total of pricer.price over every amount. */
    public static long total(Pricer pricer, long[] amounts) {
        long total = 0;
        for (long amount : amounts) {
            total += pricer.price(amount);
        }
        return total;
    }

    /** One pass with a rotating pricer mix (the megamorphic call site). */
    public static long mixedTotal(Pricer[] pricers, long[] amounts) {
        long total = 0;
        for (int i = 0; i < amounts.length; i++) {
            total += pricers[i % pricers.length].price(amounts[i]);
        }
        return total;
    }

    /**
     * The escape-analysis kernel: allocates one small temporary holder per
     * priced amount. With escape analysis the allocation is scalar-replaced
     * and never reaches the heap; with -XX:-DoEscapeAnalysis every call
     * allocates. Identical results either way — that exactness is the
     * point (the optimization must never change the answer).
     */
    public static long totalWithHolder(Pricer pricer, long[] amounts) {
        long total = 0;
        for (long amount : amounts) {
            Holder holder = new Holder(pricer.price(amount));
            total += holder.value;
        }
        return total;
    }

    static final class Holder {
        final long value;

        Holder(long value) {
            this.value = value;
        }
    }
}
